# Numpy Tutorial

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


import numpy

In [3]:
import numpy as np

In [5]:
myarr = np.array([3,6,32,7])

In [6]:
myarr

array([ 3,  6, 32,  7])

In [9]:
myarr = np.array([3,6,39,7], np.int8)

In [10]:
myarr

array([ 3,  6, 39,  7], dtype=int8)

In [15]:
myarr = np.array([[3,6,39,7],[1,4,5,8]], np.int8)

In [16]:
myarr[0][1]

np.int8(6)

In [17]:
myarr.dtype

dtype('int8')

In [18]:
myarr.shape

(2, 4)

In [19]:
myarr[0,1] = 45

In [20]:
myarr

array([[ 3, 45, 39,  7],
       [ 1,  4,  5,  8]], dtype=int8)

# Array Creation : Conversion from other Python Structures

In [28]:
listarray = np.array([[1,2,3],[4,5,6],[9,2,4]])

In [23]:
listarray.dtype

dtype('int64')

In [24]:
listarray.size

9

In [30]:
listarray.shape

(3, 3)

In [31]:
np.array({34,34,56})

array({56, 34}, dtype=object)

# Array Creation : Intrinsic numpy array creation objects

In [32]:
zeroz = np.zeros((2,5))

In [35]:
zeroz # create an array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
 rng = np.arange(15) #create an array from 0-14

In [39]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
lspace = np.linspace(1,5,12)  # create an array from 1-5 of 12 elements equally spaced

In [43]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [44]:
emp = np.empty((4,6))

In [45]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.33511018e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.37962320e-306, 1.29060871e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 6.89804133e-307, 9.34608432e-307,
        1.78019625e-306, 1.11261095e-306, 1.42410974e-306]])

In [51]:
emp_like = np.empty_like(lspace) #creates a new array with the same shape and type as a given array (the prototype), but without initializing its entries.

In [50]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [55]:
del lspace #deleting lspace from memory

In [58]:
ide = np.identity(2)

In [59]:
ide

array([[1., 0.],
       [0., 1.]])

In [60]:
arr = np.arange(99)

In [61]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
arr = arr.reshape(3,33) # multiplying this should match with the size of original array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [68]:
arr = arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [69]:
arr.shape

(99,)

In [70]:
x = [[1,2,3],[4,5,6],[7,1,10]]

In [71]:
ar = np.array(x)

In [72]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  1, 10]])

In [73]:
ar.sum(axis = 0)

array([12,  8, 19])

In [74]:
ar.sum(axis = 1)

array([ 6, 15, 18])

In [76]:
ar.T #Transpose of matrix

array([[ 1,  4,  7],
       [ 2,  5,  1],
       [ 3,  6, 10]])

In [77]:
ar.flat

In [78]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
10


In [79]:
ar.ndim

2

In [80]:
ar.size

9

In [81]:
ar.nbytes # total number of bytes covered by elements of numpy array

72

In [88]:
one = np.array([1,7,4,5,6])

In [89]:
one.argmax()

np.int64(1)

In [90]:
one.argmin()

np.int64(0)

In [101]:
one.argsort() #sort the array

array([0, 2, 3, 4, 1])

In [103]:
arr.argmax()

np.int64(98)

In [105]:
arr.argmin()

np.int64(0)

In [106]:
arr.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [107]:
ar1 = np.array([[1,2,3],[4,5,6]])

In [110]:
ar2 = np.array([[8,9,0],[2,3,4]])

In [111]:
ar1 + ar2 #array addition

array([[ 9, 11,  3],
       [ 6,  8, 10]])

In [112]:
[1,2,3] + [1,4,5]  #extends the list, this is not array

[1, 2, 3, 1, 4, 5]

In [113]:
ar1 * ar2 #multiply array

array([[ 8, 18,  0],
       [ 8, 15, 24]])

In [114]:
ar1 - ar2

array([[-7, -7,  3],
       [ 2,  2,  2]])

In [115]:
ar1 / ar2

C:\Users\manoj\AppData\Local\Temp\ipykernel_1960\1791702316.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1 / ar2


array([[0.125     , 0.22222222,        inf],
       [2.        , 1.66666667, 1.5       ]])

In [116]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 3.16227766]])

In [121]:
np.where(ar1 >  5)

(array([1]), array([2]))

In [122]:
np.count_nonzero(ar)

9

In [123]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [124]:
import sys

In [125]:
ch_ar = [0,4,55,2]

In [128]:
np_ar = np.array(ch_ar)

In [131]:
sys.getsizeof(1) #retuns the size of integer 1 

28

In [132]:
len(np_ar)

4

In [134]:
np_ar.itemsize * np_ar.size

32